### ISSUE TITLE
Roadmap of v0.1.0

### ISSUE THREAD

**Issue by xingrz** [DTrejo/node-authors#5]
Thanks @DTrejo for trusting me and allowing me to maintenance this project. Here's a roadmap that I'm planning to do.

Some of these features were originally implemented in [xingrz/node-contributors](https://github.com/xingrz/node-contributors) and I'm planning to merge them into node-authors.
- [x] Better handles large amount of git log using streaming api
- [ ] JSON and plain text support
- [ ] Writing generated content to file
- [ ] Updates AUTHORS/README.md/package.json automatically #1 
- [ ] Project stuffs (unit tests, Travis-CI integrating, etc...)
- [x] Use v3 [Search API](http://developer.github.com/v3/search/#search-users) instead of deprecated Legacy Search API. #4 #6 

This may be finished before Feburary. Since tons of changes may be made on the project, the version number is increased to 0.1.0.
